name: manutd_profile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  carousel_slider: 4.0.0
  google_fonts: 2.1.0
  image_stack: 2.1.0
  font_awesome_flutter: 9.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_native_splash: 1.3.1
  flutter_launcher_icons: 0.9.2
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/images/ic_logo.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/ic_logo.png"
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

